spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
mybatis-plus:
  #对应mapper路劲
  mapper-locations: classpath*:mapper/*.xml
  type-handlers-package: com.github.viqbgrg.springbootoverseer.mybatis.typehandler
server:
  servlet:
    context-path: /api
springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        use-model-v3: false