logging:
  file:
    path: D:/logs/
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1/overseer?serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver