logging:
  file:
    path: D:/logs/
    max-size: 10KB
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/overseer?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver