logging:
  file:
    path: D:/logs/
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1/overseer?serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
#    username: root
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true