package com.github.viqbgrg.springbootoverseer.mapper;

import com.github.viqbgrg.springbootoverseer.model.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 24 19:38:20 CST 2020
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("username") String username, @Param("email") String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 24 19:38:20 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 24 19:38:20 CST 2020
     */
    User selectByPrimaryKey(@Param("id") Integer id, @Param("username") String username, @Param("email") String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 24 19:38:20 CST 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Dec 24 19:38:20 CST 2020
     */
    int updateByPrimaryKey(User record);
}